### ISSUE TITLE
Cannot load YAFC - unable to load SDL2.dll

### ISSUE THREAD

**Issue by veger** [veger/yafc-ce#1]
@LoneWolfProductions wrote:

your modified version of YAFC is throwing this error.
It seems something is reffering to your folder structure on your HD?

![Annotation 2022-01-26 131442](https://user-images.githubusercontent.com/30441722/151161311-6b5aa97e-95cf-44f9-9b9d-fb14d9713cb6.png)

**Comment by veger** [comment]
hm... looks like it cannot find the SDL2.dll did you install it?

And on what OS are you running? (I only have access (and thus tested) Linux)
For Linux/MacOS the ShadowTheAge wrote [this page for installing](https://github.com/ShadowTheAge/yafc/blob/master/Docs/LinuxOsxInstall.md) the required libraries. 
I use Arch Linux and used `pacman -S sdl2 sdl2_iamge sdl2_ttf` to install the required sdl2 libraries.

**Comment by LoneWolfProductions** [comment]
Windows.

I downloaded you latest windows.zip release.
But that folder its showing isn't mine

**Comment by veger** [comment]
I don't know much about C#/.Net so I don't know why these references of my local HDD are (still) present... I guess there is some setting for this? I'll take a look.
But AFAIK it should not influence the workings of the application..?

**Comment by LoneWolfProductions** [comment]
Thank you,

I was really hoping to test/see what you improved as the orignal Yafc waits until you can add it is a plugin.
Thats why i try to download it here ;)

**Comment by veger** [comment]
I see they are not present in the Windows.zip (when comparing to the releases of ShadowTheAge).
I'll check how I can/should include them and do a new release to fix the issue (if you cannot wait you can grab them and copy them next to the other (extracted) files: SDL2.dll, SDL2_image.dll and SDL2_tff.dll seems missing)

**Comment by veger** [comment]
> I was really hoping to test/see what you improved as the orignal Yafc waits until you can add it is a plugin.
> Thats why i try to download it here ;)

Personally I cannot live without anymore... :wink: Being able to have an overview of all production tabs and tweaking the items shared between them in a single page is a _huge_ time saver on big(ger) factories.

**Comment by veger** [comment]
I should have fixed the Windows.zip package, now it includes the SDL2 DLLs (and some others that were missing).
Can you try re-downloading from the (same) release again?

**Comment by LoneWolfProductions** [comment]
I was typing this when you replyed. I will try to redownload and perhaps what typed under here can be ignored then ;)

> I see they are not present in the Windows.zip (when comparing to the releases of ShadowTheAge). I'll check how I can/should include them and do a new release to fix the issue (if you cannot wait you can grab them and copy them next to the other (extracted) files: SDL2.dll, SDL2_image.dll and SDL2_tff.dll seems missing)

I tried to copy them from the orignal yafc but it keeps trowing an error.
I then copied all files from the orignal yafc skipping the excisting ones into your folder.

it now seems to be running but it keeps an console window open

![image](https://user-images.githubusercontent.com/30441722/151171640-ea96df3c-c279-403a-98bf-e2c23492e553.png)

it seems to slow down the loading very hard. (3min in already :p)

**Comment by veger** [comment]
> I then copied all files from the orignal yafc skipping the excisting ones into your folder.

There were some other DLLs that were missing, I fixed the 'build' script https://github.com/ShadowTheAge/yafc/pull/151 to include them when not building on a Windows host (as I am not). So I guess/assume it works not, if not please post the new errors and we can check it out

**Comment by LoneWolfProductions** [comment]
Ok its working now (redownloaded)

The only thing is that it keeps that console window open (debug setting?) but its loading fast now.
But I can live with that ;)

Thanks for the help/time I'm gonna play now with these new options ;)

**Comment by LoneWolfProductions** [comment]
10 min in I think. I'm loving it!!!! (you can close this thread as solved :p )

Very nice work, this is indeed very much a great factory overview (and i like the only show issues )
Thank you for making this moddification publicly available.
