### ISSUE TITLE
[BUG] Summary view not adjusting to window size

### ISSUE THREAD

**Issue by LoneWolfProductions** [veger/yafc-ce#2]
When maximizing the window, the summary view area does not grow with the window but cuts off.
Leaving the area under the red line (that i drew) unused

![Annotation 2022-01-27 151425](https://user-images.githubusercontent.com/30441722/151376335-821b52f4-567b-44b4-9fa8-dd6cfe81ad4f.png)

**Comment by veger** [comment]
It is a known issue (I hate it myself as well as I have a whole bunch of tabs that I need to summarize), but it seems impossible to resize the 'panel' with the window height (at least I cannot figure it out)

**Comment by veger** [comment]
I gave it another stab, and this (sort of) works (on my machine :wink: )

**Comment by veger** [comment]
You can try it in [the v0.6.0-veger.2 release](https://github.com/veger/yafc/releases/tag/v0.6.0-veger.2)

**Comment by LoneWolfProductions** [comment]
I'll will take a look when i got the time.

**Comment by veger** [comment]
Was it fixed? I am (planning to) move to YAFC-CE, so I want to archive this fork soon. So it would be nice to have this ticket closed before :smile:

**Comment by LoneWolfProductions** [comment]
I downloaded it fast on my work pc at work.

Seems to be ok now. sorry for the very late replay to the ticket but i had a big break and also am just back to factorio and py

I would love to have this in the CE edition as i can have pages adjust their production to each other in this version.

The summary that is implement in the original YAFC is bugged
