### ISSUE TITLE
[Feature request] clicking summary icon does not auto refresh the summary

### ISSUE THREAD

**Issue by LoneWolfProductions** [veger/yafc-ce#3]
When clicking an icon in the summary it auto adjust to the new needs of other sheets.
But you need always to un-tick/tick "only show issues" to update everything.

It would be nice that it would auto update/recalculate after the icon click.

**Comment by LoneWolfProductions** [comment]
I have no clue what changed but all of a sudden this is now happening like requested.

Maybe some condition that was preventing it before?

**Comment by veger** [comment]
no idea, but good to hear it works now :smile:
